name: Deploy to Apps Script

on:
  push:
    branches: [main]
    paths:
      - 'apps-script/**'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Restore clasp credentials
        env:
          CLASPRC: ${{ secrets.APP_SCRIPT }}
        run: echo "$CLASPRC" > "$HOME/clasprc.json"

      - name: Push to Apps Script
        working-directory: apps-script
        env:
          clasp_config_auth: /home/runner/clasprc.json
        run: clasp push -f

      - name: Deploy new version to the live Web App
        working-directory: apps-script
        env:
          clasp_config_auth: /home/runner/clasprc.json
        run: clasp deploy --deploymentId AKfycbxGXYHXLjZlrnIpIaYkaIO5I-U1W1wOCbuVarEk9kRYKc7AR8MXRJUpmEyOTIWhzyp0 --description "Auto-deploy from GitHub Actions"
